# Generated by Django 3.0.7 on 2020-07-19 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200711_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
