# Generated by Django 3.0.7 on 2020-07-19 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(default='No description given', max_length=500, null=True),
        ),
    ]
